config/routes.rb
Rails.application.routes.draw do
  resources :markets

  resources :forexes

  resources :banks

  resources :changers

  resources :movers

  resources :share_indices

  resources :stock_quotes

  resources :securities

end

app/controllers/share_indices_controller.rb
class ShareIndicesController < ApplicationController
  before_action :set_share_index, only: [:show, :edit, :update, :destroy]

  # GET /share_indices
  # GET /share_indices.json
  def index
    @share_indices = ShareIndex.all
  end

  # GET /share_indices/1
  # GET /share_indices/1.json
  def show
  end

  # GET /share_indices/new
  def new
    @share_index = ShareIndex.new
  end

  # GET /share_indices/1/edit
  def edit
  end

  # POST /share_indices
  # POST /share_indices.json
  def create
    @share_index = ShareIndex.new(share_index_params)

    respond_to do |format|
      if @share_index.save
        format.html { redirect_to @share_index, notice: 'Share index was successfully created.' }
        format.json { render :show, status: :created, location: @share_index }
      else
        format.html { render :new }
        format.json { render json: @share_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /share_indices/1
  # PATCH/PUT /share_indices/1.json
  def update
    respond_to do |format|
      if @share_index.update(share_index_params)
        format.html { redirect_to @share_index, notice: 'Share index was successfully updated.' }
        format.json { render :show, status: :ok, location: @share_index }
      else
        format.html { render :edit }
        format.json { render json: @share_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /share_indices/1
  # DELETE /share_indices/1.json
  def destroy
    @share_index.destroy
    respond_to do |format|
      format.html { redirect_to share_indices_url, notice: 'Share index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share_index
      @share_index = ShareIndex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_index_params
      params.require(:share_index).permit(:all_share_index, :twenty_share_index)
    end
end

app/helpers/share_indices_helper.rb
module ShareIndicesHelper
end

app/views/share_indices/_form.html.erb
<%= form_for(@share_index) do |f| %>
  <% if @share_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share_index.errors.count, "error") %> prohibited this share_index from being saved:</h2>

      <ul>
      <% @share_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :all_share_index %><br>
    <%= f.text_field :all_share_index %>
  </div>
  <div class="field">
    <%= f.label :twenty_share_index %><br>
    <%= f.text_field :twenty_share_index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/share_indices/edit.html.erb
<h1>Editing share_index</h1>

<%= render 'form' %>

<%= link_to 'Show', @share_index %> |
<%= link_to 'Back', share_indices_path %>

app/views/share_indices/index.html.erb
<h1>Listing share_indices</h1>

<table>
  <thead>
    <tr>
      <th>All share index</th>
      <th>Twenty share index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @share_indices.each do |share_index| %>
      <tr>
        <td><%= share_index.all_share_index %></td>
        <td><%= share_index.twenty_share_index %></td>
        <td><%= link_to 'Show', share_index %></td>
        <td><%= link_to 'Edit', edit_share_index_path(share_index) %></td>
        <td><%= link_to 'Destroy', share_index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Share index', new_share_index_path %>

app/views/share_indices/new.html.erb
<h1>New share_index</h1>

<%= render 'form' %>

<%= link_to 'Back', share_indices_path %>

app/views/share_indices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>All share index:</strong>
  <%= @share_index.all_share_index %>
</p>

<p>
  <strong>Twenty share index:</strong>
  <%= @share_index.twenty_share_index %>
</p>

<%= link_to 'Edit', edit_share_index_path(@share_index) %> |
<%= link_to 'Back', share_indices_path %>