config/routes.rb
Rails.application.routes.draw do
  resources :markets

  resources :forexes

  resources :banks

  resources :changers

  resources :movers

  resources :share_indices

  resources :stock_quotes

  resources :securities

end

app/models/bank.rb
# == Schema Information
#
# Table name: banks
#
#  id               :integer          not null, primary key
#  volume           :integer
#  high             :float
#  low              :float
#  war              :float
#  window_borrowing :integer
#  created_at       :datetime
#  updated_at       :datetime
#  guid             :string(255)
#  published_at     :datetime
#

class Bank < ActiveRecord::Base
	scope :war, -> { where(["war != ?", 0 ]) }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Bank.create! row.to_hash
    end
  end

  	def self.update_from_feed(feed_url)
	  feed = Feedjira::Feed.fetch_and_parse(feed_url)
    unless feed.is_a?(Fixnum)
      add_entries(feed.entries)
    else
      puts feed.inspect
    end
	end

  def self.update_from_feed_continuously(feed_url,delay_interval=2.minutes)
  	feed = Feedjira::Feed.fetch_and_parse(feed_url)
  	add_entries(feed.entries)

  	loop do
  		sleep delay_interval
  		feed = Feedjira::Feed.update(feed_url)
  		add_entries(feed.new_entries) if feed.updated?
  	end
  end

  private


  def self.add_entries(entries)
  	entries.each do | entry |
      c = entry.updated.to_s
      unless exists? guid: entry.id+c
        b = entry.content
        content = b.scan(/(?<=[ *])-?\d[\d.]+/).map(&:to_f)
        Bank.create!(
          volume: content[0],
          high: content[1],
          low: content[2],
          war: entry.updated,
          day: entry.updated,
          guid: entry.id+c
        );
      end       
    end
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  # POST /banks.json
  def create
    @bank = Bank.new(bank_params)

    respond_to do |format|
      if @bank.save
        format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
        format.json { render :show, status: :created, location: @bank }
      else
        format.html { render :new }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banks/1
  # PATCH/PUT /banks/1.json
  def update
    respond_to do |format|
      if @bank.update(bank_params)
        format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank }
      else
        format.html { render :edit }
        format.json { render json: @bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.json
  def destroy
    @bank.destroy
    respond_to do |format|
      format.html { redirect_to banks_url, notice: 'Bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:volume, :high, :low, :war, :window_borrowing)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :volume %><br>
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.text_field :high %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.text_field :low %>
  </div>
  <div class="field">
    <%= f.label :war %><br>
    <%= f.text_field :war %>
  </div>
  <div class="field">
    <%= f.label :window_borrowing %><br>
    <%= f.number_field :window_borrowing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<h1>Listing banks</h1>

<table>
  <thead>
    <tr>
      <th>Volume</th>
      <th>High</th>
      <th>Low</th>
      <th>War</th>
      <th>Window borrowing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= bank.volume %></td>
        <td><%= bank.high %></td>
        <td><%= bank.low %></td>
        <td><%= bank.war %></td>
        <td><%= bank.window_borrowing %></td>
        <td><%= link_to 'Show', bank %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Destroy', bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Volume:</strong>
  <%= @bank.volume %>
</p>

<p>
  <strong>High:</strong>
  <%= @bank.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @bank.low %>
</p>

<p>
  <strong>War:</strong>
  <%= @bank.war %>
</p>

<p>
  <strong>Window borrowing:</strong>
  <%= @bank.window_borrowing %>
</p>

<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>