config/routes.rb
Rails.application.routes.draw do
  resources :markets

  resources :forexes

  resources :banks

  resources :changers

  resources :movers

  resources :share_indices

  resources :stock_quotes

  resources :securities

end

app/models/security.rb
# == Schema Information
#
# Table name: securities
#
#  id            :integer          not null, primary key
#  security      :string(255)
#  security_code :string(255)
#  category      :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Security < ActiveRecord::Base
	has_many :stock_quotes, dependent: :destroy
end

app/controllers/securities_controller.rb
class SecuritiesController < ApplicationController
  before_action :set_security, only: [:show, :edit, :update, :destroy]

  # GET /securities
  # GET /securities.json
  def index
    @securities = Security.all
  end

  # GET /securities/1
  # GET /securities/1.json
  def show
  end

  # GET /securities/new
  def new
    @security = Security.new
  end

  # GET /securities/1/edit
  def edit
  end

  # POST /securities
  # POST /securities.json
  def create
    @security = Security.new(security_params)

    respond_to do |format|
      if @security.save
        format.html { redirect_to @security, notice: 'Security was successfully created.' }
        format.json { render :show, status: :created, location: @security }
      else
        format.html { render :new }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /securities/1
  # PATCH/PUT /securities/1.json
  def update
    respond_to do |format|
      if @security.update(security_params)
        format.html { redirect_to @security, notice: 'Security was successfully updated.' }
        format.json { render :show, status: :ok, location: @security }
      else
        format.html { render :edit }
        format.json { render json: @security.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /securities/1
  # DELETE /securities/1.json
  def destroy
    @security.destroy
    respond_to do |format|
      format.html { redirect_to securities_url, notice: 'Security was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security
      @security = Security.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def security_params
      params.require(:security).permit(:security, :security_code, :category)
    end
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/securities/_form.html.erb
<%= form_for(@security) do |f| %>
  <% if @security.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@security.errors.count, "error") %> prohibited this security from being saved:</h2>

      <ul>
      <% @security.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :security %><br>
    <%= f.text_field :security %>
  </div>
  <div class="field">
    <%= f.label :security_code %><br>
    <%= f.text_field :security_code %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/securities/edit.html.erb
<h1>Editing security</h1>

<%= render 'form' %>

<%= link_to 'Show', @security %> |
<%= link_to 'Back', securities_path %>

app/views/securities/index.html.erb
<h1>Listing securities</h1>

<table>
  <thead>
    <tr>
      <th>Security</th>
      <th>Security code</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @securities.each do |security| %>
      <tr>
        <td><%= security.security %></td>
        <td><%= security.security_code %></td>
        <td><%= security.category %></td>
        <td><%= link_to 'Show', security %></td>
        <td><%= link_to 'Edit', edit_security_path(security) %></td>
        <td><%= link_to 'Destroy', security, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Security', new_security_path %>

app/views/securities/new.html.erb
<h1>New security</h1>

<%= render 'form' %>

<%= link_to 'Back', securities_path %>

app/views/securities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Security:</strong>
  <%= @security.security %>
</p>

<p>
  <strong>Security code:</strong>
  <%= @security.security_code %>
</p>

<p>
  <strong>Category:</strong>
  <%= @security.category %>
</p>

<%= link_to 'Edit', edit_security_path(@security) %> |
<%= link_to 'Back', securities_path %>