config/routes.rb
Rails.application.routes.draw do
  resources :markets

  resources :forexes

  resources :banks

  resources :changers

  resources :movers

  resources :share_indices

  resources :stock_quotes

  resources :securities

end

app/models/market.rb
# == Schema Information
#
# Table name: markets
#
#  id                    :integer          not null, primary key
#  equity_turnover       :float
#  market_capitalization :float
#  created_at            :datetime
#  updated_at            :datetime
#  guid                  :string(255)
#  published_at          :datetime
#

class Market < ActiveRecord::Base
	 feed_url = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	def update_from_feed(feed_url)
	  feed = Feedjira::Feed.fetch_and_parse(feed_url)
    # unless feed.is_a?(Fixnum)
    #   add_entries(feed.entries)
    # else
    #   puts feed.inspect
    # end
	end

  def self.update_from_feed_continuously(feed_url,delay_interval=2.minutes)
  	feed = Feedjira::Feed.fetch_and_parse(feed_url)
  	add_entries(feed.entries)

  	loop do
  		sleep delay_interval
  		feed = Feedjira::Feed.update(feed_url)
  		add_entries(feed.new_entries) if feed.updated?
  	end
  end

  private


  def self.add_entries(entries)
  	entries.each do | entry |
      c = entry.updated.to_s
      unless exists? guid: entry.id+c
        b = entry.content
        content = b.scan(/(?<=[ *])-?\d[\d.]+/).map(&:to_f)
        Mover.create!(
          mover: content[0],
          volume: content[1],
          published_at: entry.updated,
          guid: entry.id+c
        );
      end			  
  	end
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.all
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to markets_url, notice: 'Market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit(:equity_turnover, :market_capitalization)
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_form.html.erb
<%= form_for(@market) do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :equity_turnover %><br>
    <%= f.text_field :equity_turnover %>
  </div>
  <div class="field">
    <%= f.label :market_capitalization %><br>
    <%= f.text_field :market_capitalization %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<h1>Listing markets</h1>

<table>
  <thead>
    <tr>
      <th>Equity turnover</th>
      <th>Market capitalization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markets.each do |market| %>
      <tr>
        <td><%= market.equity_turnover %></td>
        <td><%= market.market_capitalization %></td>
        <td><%= link_to 'Show', market %></td>
        <td><%= link_to 'Edit', edit_market_path(market) %></td>
        <td><%= link_to 'Destroy', market, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Market', new_market_path %>

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render 'form' %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Equity turnover:</strong>
  <%= @market.equity_turnover %>
</p>

<p>
  <strong>Market capitalization:</strong>
  <%= @market.market_capitalization %>
</p>

<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>